image: docker:latest

stages:
- build
- release
- pre_deploy
- deploy
- post_deploy

variables:
  CONTAINER_IMAGE: $REGISTRY_URL/test/manager:latest
  
before_script:
- echo $CI_BUILD_REF_NAME

build:
  image: maven:3-jdk-8
  stage: build
  script: mvn install -B
  artifacts:
    paths:
      - target/test-manager.war

release:
  stage: release
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY_URL
    - docker build -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE
    
pre_deploy:
  stage: pre_deploy
  script:
    - docker ps -qf name=manager | xargs docker stop
    - docker ps -aqf name=manager | xargs docker rm -f
  allow_failure: true

deploy:
  stage: deploy
  script:
    - docker pull $CONTAINER_IMAGE
    - docker run -d --name manager $CONTAINER_IMAGE
    
post_deploy:
  stage: post_deploy
  script:
    - docker images -qf dangling=true | xargs docker rmi -f
  allow_failure: true
