version: '3'

services:
  gitlab-runner:
    image: nohaapav/docker-gitlab-runner:latest
    environment:
      - GITLAB_HOST=${GITLAB_HOST}
      - GITLAB_IP=${GITLAB_IP}
      - GITLAB_RUNNER_TOKEN=${GITLAB_RUNNER_TOKEN}
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - net
    deploy:
      mode: global
      placement:
        constraints: [node.role == worker]

networks:
  net:
    external:
      name: ci_net
