image: docker:latest

stages:
- build
- release

variables:
  CONTAINER_IMAGE: $REGISTRY_URL/test/manager:$CI_BUILD_REF_NAME
  
before_script:
- echo $CI_BUILD_REF_NAME

build:
  image: maven:3-jdk-8
  stage: build
  script: mvn install -B
  artifacts:
    paths:
      - target/test-manager.war
release:
  stage: release
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $REGISTRY_URL
    - docker build -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE
